### ISSUE TITLE
建议：打tag发布版本号

### ISSUE THREAD

**Issue by shaunthegeek** [greedying/zhima#1]
建议：打tag发布版本，否则master一旦变动，影响所有人使用。

版本号规则：语义化版本 2.0.0 http://semver.org/lang/zh-CN/

参考：https://github.com/sinkcup/aliyun-sms-php-sdk-composer/tags

**Comment by greedying** [comment]
哈哈 ，谢谢，终于有人关注了，泪流满面。因为一直没时间写，其实一版也没完成。后续测试一下，加上日志，我再打tag吧

**Comment by shaunthegeek** [comment]
没关系啊，现在最基本的功能可以用了吧？那就先打个 0.1.0 ，大家好安装啊。

**Comment by shaunthegeek** [comment]
啊！你好像没有发布到 composer商店啊？那安装不方便啊。

参考我的已经发布了：
https://packagist.org/packages/sinkcup/aliyun-sms

**Comment by greedying** [comment]
暂时没有发布到composer，发布后我会更新这里的回复。

不过composer支持vcs模式，可以这样使用
"repositories": [
    {"type": "vcs", "url": "https://github.com/greedying/zhima"},
]

在MD文件中也有说明

**Comment by greedying** [comment]
已经打tag，并发布到composer库
